name: Label Sync
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/labels.yml'
jobs:
  labeler:
    name: Synchronize labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}